# Preprocessing of Mask data

In [45]:
!pip install opencv-python
import cv2
import os

In [46]:
data_path='Mask data'


In [47]:
categories=os.listdir(data_path)                # List of subdirectories (categories),ie, here 2 folders with mask and without mask
labels=[i for i in range(len(categories))]       # Numerical labels for each category,ie,len(catagories)=2. range(len(catagories))= range(2)=0,1.ie, here assign values 0&1 to without mask and with mask accordingly
label_dict=dict(zip(categories,labels))         # Dictionary mapping category names to numerical labels.ie,here for mask data ,label 1, and without mask label 2


In [48]:
print(label_dict)

{'without_mask': 0, 'with_mask': 1}


In [49]:
print(categories)

['without_mask', 'with_mask']


In [50]:
print(labels)

[0, 1]


In [51]:
img_size=100
data=[]          # create a empty list data
target=[]        #create a empty list target 

In [52]:
for category in categories:
    folder_path=os.path.join(data_path,category)   #join the specified paths,data_path & catagory. ie here joins mask data + without mask & mask data+ with mask
    img_names=os.listdir(folder_path)              #here creating alist, ie,every image names in 2 folders(without mask &with mask)
    for img_name in img_names:
        img_path=os.path.join(folder_path,img_name)     # joins mask data+ with out mask+ image name (all image in that folder) & mask data+ withmask+all images
        img=cv2.imread(img_path)                          # to read an image from file specified path.
        try:
            gray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)     #convert image to grayscale
            resized=cv2.resize(gray,(img_size,img_size))  #resizing the grayscale into 100*100,#since we need a fixed common size for all the images
            data.append(resized)                          #append the resized data to previously ceated empty list 'data'
            target.append(label_dict[category])           #appending the image and the label (categorized) into the list (dataset)
        except Exception as e:
            print('Exception:',e)                         #if there is any exception will be printed here and pass to the next image

In [53]:
import numpy as np
data=np.array(data)/255.0


In [54]:
# normalizing the pixel values of the images in the NumPy array.Divides each element in the NumPy array by 255.0.Pixel values are typically in the range of 0 to 255 (for an 8-bit image), and dividing by 255 scales the values to be in the range of 0 to 1.0. Normalizing to this range can make training neural networks more stable and can help convergence during the optimization process.


In [55]:
print(data.shape)

(1376, 100, 100)


In [56]:
# (1376)  number of samples or images, (100, 100) represent the height and width of each image


In [57]:
data=np.reshape(data,(data.shape[0],img_size,img_size,1))


In [58]:
# if your original shape was (1376, 100, 100) (1376 images, each of size 100x100 pixels), after reshaping, it becomes (1376, 100, 100, 1), indicating that there is one channel for each image. 1 is the new dimension added, and it typically represents the number of channels. In this case, it is used for grayscale images, where there is only one channel.


In [59]:
target=np.array(target)
target

array([0, 0, 0, ..., 1, 1, 1])

In [60]:
from keras.utils import np_utils
new_target=np_utils.to_categorical(target)
print(new_target)

[[1. 0.]
 [1. 0.]
 [1. 0.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]


In [61]:
new_target

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       ...,
       [0., 1.],
       [0., 1.],
       [0., 1.]], dtype=float32)

In [62]:
np.save('data',data)
np.save('target',new_target)